### ISSUE TITLE
入力の形式について

### ISSUE THREAD

**Issue by equal-l2** [Aring8510/syoringi#3]
[`いっぺんに入力させようとしたけどうまくいかなかった.修正求む`](https://github.com/Aring8510/syoringi/blob/c6415687e8b25df01dc6cf9678082ec0ce2bfa86/main.c#L453)なんですが、理想としてはどのような入力形式で受け取りたいんでしょう？

**Comment by Aring8510** [comment]
動かす前の駒の座標と動かした後の駒の座標と成るか成らないかの情報があればいいかと思います．例えば(1,6)の駒を(1,7)へ成るときは，コンマ区切りなら1,6,1,7,1などの入力でそれぞれの数字を変数に格納出来たらオーケーです．
ただ，持ち駒を打つ時どのように入力させたらいいかを考えていなかったんですけど，なにかいい方法などありますか？僕が思いついたのは最初の入力を-1にして次の数字で駒の種類を指定させればいいかなと思いました．
まあ，なにはともあれ一度の入力で5つの数字を5つの変数に格納するやり方を教えてくれたら助かります．

**Comment by equal-l2** [comment]
`scanf`を使えば一度に複数の値を取得することもできます。

今、こういうコードがあります。
これはもちろん改行やスペースで区切られた4つの整数を受け取るコードです。
```c
scanf("%d", &beforeX);
scanf("%d", &beforeY);
scanf("%d", &afterX);
scanf("%d", &afterY);
```
<br>

同等の動作を次のコードで行うことができます。
```c
scanf("%d %d %d %d", &beforeX, &beforeY, &afterX, &afterY);
```
(いっぺんに入力を受け取るので、各々の入力に`printf`を挟んだりはできなくなりますが……)

<br>

コンマ区切りで受け取るなら次のように。
```c
scanf("%d , %d , %d , %d", &beforeX, &beforeY, &afterX, &afterY);
```
(コンマの両脇にスペースを挟まないとスペース等が混ざったときに死にます)

**Comment by Aring8510** [comment]
いつものことながらアドバイスありがとうございます．参考にしながらのちほど修正します．Issueは修正後閉じます．

**Comment by Aring8510** [comment]
fixed in "一括で入力可能に"
(次からはコミットメッセージからクローズするようにします)
